[package]
name = "siri_et_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
quick-xml = {version = "0.36.2", features = ["serialize"]}
chrono = { version = "0.4.38", features = ["serde"] }
