[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.108"
quote = "1.0"
proc-macro2 = "1.0"