[package]
name = "parser_unsafe"
version = "0.1.8"
edition = "2021"


[lib]
name = "parser"
crate-type = ["cdylib"]

[dependencies]
parser = { path = "../parser" }
serde_json = "1.0.132"
serde = { version = "1.0.213", features = ["derive"] }
