name: Rust CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - run: cargo test
